/* This file was generated by syncqt. */
#ifndef QT_QTOPENGL_VERSION_H
#define QT_QTOPENGL_VERSION_H

#define QTOPENGL_VERSION_STR "6.1.0"

#define QTOPENGL_VERSION 0x060100

#endif // QT_QTOPENGL_VERSION_H
