# Form implementation generated from reading ui file '/Users/xyj/.npm/ssh/UI/UI/Java_Dowmloader_OK_UI.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog_2(object):
    def setupUi(self, Dialog_2):
        Dialog_2.setObjectName("Dialog_2")
        Dialog_2.resize(505, 120)
        Dialog_2.setMinimumSize(QtCore.QSize(505, 120))
        Dialog_2.setMaximumSize(QtCore.QSize(505, 120))
        Dialog_2.setStyleSheet("QDialog{background-color: rgb(255, 255, 255);}\n"
"#pushButton{border:2px solid rgba(235, 235, 235,0);height:25px;border-radius:5px;}\n"
"#pushButton::hover{background-color: rgb(192, 192, 192);}\n"
"#pushButton::pressed{background-color: rgb(169, 169, 169);}\n"
"\n"
"#pushButton_2{background-color: rgba(255, 255, 255, 0);}")
        self.gridLayout = QtWidgets.QGridLayout(Dialog_2)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton = QtWidgets.QPushButton(Dialog_2)
        self.pushButton.setMinimumSize(QtCore.QSize(200, 30))
        self.pushButton.setMaximumSize(QtCore.QSize(200, 30))
        self.pushButton.setStyleSheet("font-size: 14px;")
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 2, 3, 1, 1)
        self.label_2 = QtWidgets.QLabel(Dialog_2)
        self.label_2.setStyleSheet("font-size: 16px;")
        self.label_2.setIndent(2)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 2, 1, 2)
        self.label = QtWidgets.QLabel(Dialog_2)
        self.label.setStyleSheet("font-size: 14px;")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 2, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem, 2, 1, 1, 2)
        self.pushButton_2 = QtWidgets.QPushButton(Dialog_2)
        self.pushButton_2.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_2.setMaximumSize(QtCore.QSize(50, 50))
        self.pushButton_2.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/ing/OK.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_2.setIcon(icon)
        self.pushButton_2.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 0, 1, 2, 1)

        self.retranslateUi(Dialog_2)
        QtCore.QMetaObject.connectSlotsByName(Dialog_2)

    def retranslateUi(self, Dialog_2):
        _translate = QtCore.QCoreApplication.translate
        Dialog_2.setWindowTitle(_translate("Dialog_2", "Dialog"))
        self.pushButton.setText(_translate("Dialog_2", "好的"))
        self.label_2.setText(_translate("Dialog_2", "提示"))
        self.label.setText(_translate("Dialog_2", "下载&配置Java完成"))
