name: 反馈一个新Bug==
description: 在这里，你可以反馈本项目的新Bug
title: "[BUG]"
labels: ["bug"]
assignees:
  - OasisAkari
body:
  - type: markdown
    attributes:
      value: |
        无论您提交的Bug有多么简单, 也请严格按照 Issue 模板填写信息, 未正确套用模板或信息不全的将不做处理. 感谢配合
  - type: checkboxes
    id: preflight
    attributes:
      label: 开始之前……
      description: 让我们看看你准备好了吗？～
      options:
        - label: 我已经认真阅读[说明文件(Githib)](https://github.com/xianyongjian080402/Minecraft-Optimal-Starter_2/blob/master/.github/ISSUE_TEMPLATE/ISSUE_GUIDELINES.md)/[说明文件(Gitee)](https://gitee.com/xian66/minecraft-optimal-starter_2/blob/master/.gitee/ISSUE_GUIDELINES.md)
          required: true
  - type: textarea
    id: description
    attributes:
      label: 错误描述
      description: 请描述你遇到的具体问题
      placeholder: 如：MOS启动器在运行时，出现了…………
    validations:
      required: true
  - type: textarea
    id: reproducing
    attributes:
      label: 复现方法
      description: 你是如何触发这个错误的
      placeholder: |
        1. 点击……
        2. 报错
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: 期望的效果
      description: 你期盼发生的结果
      placeholder: 切换页面
    validations:
      required: true
  - type: textarea
    id: expected_2
    attributes:
      label: 实际效果
      description: 实际发生的结果 (如果在 “错误描述里” 写过了，可写“见上文”)
      placeholder: 程序闪退了
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: 截图
      description: 如果有截图的话，在这里上传吧。
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: 日志
      description: 如果有必要上传日志的话，在这里上传吧 (强烈建议上传)
    validations:
      required: false
  - type: textarea
    id: other
    attributes:
      label: 备注
      description: 在这里写上备注
      placeholder: 什么都可以哦，没有那就算了吧。
    validations:
      required: false
  - type: textarea
    id: other_2
    attributes:
      label: 留言
      description: 你还想告诉我们什么？
      placeholder: 什么都可以哦，没有那就算了吧。
    validations:
      required: false