name: 提出一个新建议
description: 在这里，你可以给本项目提出建议
title: "[建议]"
labels: ["recommendation"]
assignees:
  - OasisAkari
body:
  - type: markdown
    attributes:
      value: |
        无论您提交的建议有多么简单, 也请严格按照 Issue 模板填写信息, 未正确套用模板或信息不全的将不做处理. 感谢配合
  - type: checkboxes
    id: preflight
    attributes:
      label: 开始之前……
      description: 让我们看看你准备好了吗？～
      options:
        - label: 我已经认真阅读[说明文件(Githib)](https://github.com/xianyongjian080402/Minecraft-Optimal-Starter_2/blob/master/.github/ISSUE_TEMPLATE/ISSUE_GUIDELINES.md)/[说明文件(Gitee)](https://gitee.com/xian66/minecraft-optimal-starter_2/blob/master/.gitee/ISSUE_GUIDELINES.md)
          required: true
  - type: textarea
    id: description
    attributes:
      label: 需求/意见说明
      description: 请说明你的建议
      placeholder: 添加…………
    validations:
      required: true
  - type: textarea
    id: description_2
    attributes:
      label: 建议描述 (详细)
      description: 请详细描述你的建议
      placeholder: 如：为MOS启动器添加…………
    validations:
      required: true
  - type: textarea
    id: description_3
    attributes:
      label: 解决什么痛点/带来什么收益
      description: 解决什么痛点/带来什么收益
      placeholder: 如：可以解决/有利于…………
    validations:
      required: true
  - type: textarea
    id: reproducing
    attributes:
      label: 实现方法
      description: 你认为，我可以怎么实现？
      placeholder: |
        1. 先……
        2. 然后……
    validations:
      required: false
  - type: textarea
    id: expected
    attributes:
      label: 要用到的API/库
      description: 为了实现，要用到的API/库
      placeholder: requests库/……的API
    validations:
      required: false
  - type: input
    id: expected_2
    attributes:
      label: 帮助文档
      description: 你有这个库/接口的帮助文档吗? (这有助于开发人员快速开发哦)
      placeholder: https://doc.qt.io/
    validations:
      required: false
  - type: textarea
    id: other
    attributes:
      label: 备注
      description: 在这里写上备注
      placeholder: 什么都可以哦，没有那就算了吧。
    validations:
      required: false
  - type: textarea
    id: other_2
    attributes:
      label: 留言
      description: 你还想告诉我们什么？
      placeholder: 什么都可以哦，没有那就算了吧。
    validations:
      required: false