/* This file was generated by syncqt. */
#ifndef QT_QTUITOOLS_VERSION_H
#define QT_QTUITOOLS_VERSION_H

#define QTUITOOLS_VERSION_STR "6.1.0"

#define QTUITOOLS_VERSION 0x060100

#endif // QT_QTUITOOLS_VERSION_H
